version: '3.5'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    tty: true

  db:
    image: mysql
    restart: always
    environment:
       MYSQL_PASSWORD: password
